version: '3'
services:
  db:
    image: ankane/pgvector:v0.4.4
    ports:
      - '5432:5432'
    volumes:
      - .postgres:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/scripts:/scripts
    environment:
      POSTGRES_PASSWORD: secret
    tty: true
    stdin_open: true
    networks:
      - my-network
  api:
    build:
      context: ./api
      dockerfile: containers/development/Dockerfile
    command: /bin/bash -c "poetry install && poetry run python manage.py runserver 0:5000"
    ports:
      - '5000:5000'
    volumes:
      - ./api:/api
    environment:
      - DOCKER_POSTGRES_HOST=db
    depends_on:
      - db
    tty: true
    stdin_open: true
    env_file: .env
    networks:
      - my-network
  web:
    build:
      context: ./web
      dockerfile: containers/development/Dockerfile
    command: /bin/sh -c "yarn install && yarn dev"
    ports:
      - '8100:8100'
    volumes:
      - ./web:/web
      - /web/node_modules
    networks:
      - my-network
networks:
  my-network:
    external: true
